# Generated by Django 3.1 on 2020-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200826_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
