# Generated by Django 3.1 on 2020-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200827_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
