# Generated by Django 3.1 on 2020-09-01 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_taskmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
