# Generated by Django 3.1 on 2020-08-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='user',
        ),
    ]
