# Generated by Django 3.1 on 2020-08-20 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20200819_0904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeModel',
            new_name='TaskModel',
        ),
    ]
